### ISSUE TITLE
Deflater

### ISSUE THREAD

**Issue by ArmynC** [Lymphatus/libcaesium#11]
**Hello**! Based on [these tests](https://rreverser.com/bringing-oxipng-to-squoosh/), shouldn't  _[libdeflater](https://github.com/adamkewley/libdeflater)_ be a viable option? Thanks!

**Comment by Lymphatus** [comment]
Libcaesium is already using OxiPNG

**Comment by ArmynC** [comment]
I meant OxiPNG with libdeflater as a direct option.

**Comment by Lymphatus** [comment]
Oh I'm sorry, I missed the point. I think when I started developing the library there was no libdeflate option for oxipng, but now seems a very good option. I'll try it out myself and see the results. Thanks for pointing it out!
