### ISSUE TITLE
HEIC Support

### ISSUE THREAD

**Issue by austinclamon** [Lymphatus/libcaesium#14]
HEIC support would be a welcome addition on systems that have the codec such as macos and windows.

**Comment by Lymphatus** [comment]
It's been a long time and after trying to make it work, I must close this as not planned.
It's really hard to make it work on Windows. I've done some experiments in Linux/macOS with a degree of success, but Windows gave me a lot of headache. I might be coming back to this in the future, but for now I'm not planning to support it.
