### ISSUE TITLE
JPEG Chroma subsampling

### ISSUE THREAD

**Issue by ltcdatagonza** [Lymphatus/libcaesium#15]
Hi!
A good way of reducing JPEG size's with acceptable quality loss is chroma subsampling.
It would be good in adition to the quality slider, to be able to choose from:
No subsampling 4:4:4
Low 4:2:2
Medium 4:2:0
High 4:1:1
So when is needed with a little more quality loss, there is a way to further reduce the jpeg sizes.

**Comment by Lymphatus** [comment]
Very very late, but I added an option for Chroma Subsampling in https://github.com/Lymphatus/libcaesium/commit/7d2d387c397cc74365d37ff9c58505bfd6038438. I'm no expert so I'm gonna test it a little bit more before releasing the v0.12.0 with that option.
