### ISSUE TITLE
Publish crate?

### ISSUE THREAD

**Issue by blopker** [Lymphatus/libcaesium#18]
Hey! I'm making a little app based on this library (https://github.com/blopker/alic) and it's working great so far. Although, right now I'm just pulling this library right off of Git `main` here. It would be nice if I could get it as a versioned crate, so I can check for breaking changes more easily. Unless it's already published, and I can't find it for some reason?

Anyway, thanks for making this!

**Comment by Lymphatus** [comment]
I'm planning on publishing on Crate but I'd like to first polish a bit the code, which has a lot of place for improvements. Also I'd like to document it a bit better for people using it.

For now you can use `libcaesium = { git = "https://github.com/Lymphatus/libcaesium.git", tag = "0.15.1" }` (as you already are) as I only publish tags on new releases.

**Comment by blopker** [comment]
Great, good to know! Right, I did use the tagged version, but forgot until now. The new tags just don't show up with `cargo outdated` so it didn't show there were updates. I'll just check here until this is published.

**Comment by Lymphatus** [comment]
[Here it is](https://crates.io/crates/libcaesium)
