### ISSUE TITLE
wrong libjpeg used when stock libjpeg is installed in /usr/local/lib/

### ISSUE THREAD

**Issue by nosilver4u** [Lymphatus/libcaesium#6]
So I've had this issue on both Debian 8 & 9 at this point, and it is simply that I have mozjpeg installed (in the usual /opt/mozjpeg/ location), and stock libjpeg 9c installed also.

This results in the following (incorrect) linkage for caesiumclt:
```        linux-vdso.so.1 (0x00007ffc24705000)
        libcaesium.so => /usr/lib/libcaesium.so (0x00007fb2c992f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb2c962b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2c928c000)
        libjpeg.so.9 => /usr/local/lib/libjpeg.so.9 (0x00007fb2c9052000)
        libturbojpeg.so.0 => /opt/mozjpeg/lib64/libturbojpeg.so.0 (0x00007fb2c8da3000)
        libzopflipng.so.1 => /usr/lib/libzopflipng.so.1 (0x00007fb2c8b6f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb2c9d7e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb2c87ed000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb2c85d6000)
```

CaesiumCLT will then report this error when attempting to compress an image:
"Wrong JPEG library version: library is 90, caller expects 62"

Moving this line after the mozjpeg linkage in CMakeLists.txt solves the issue for me:
`link_directories(/usr/local/lib)`

At some point, I may just have to write the fix into my deployment script so that I'm not stuck on .10.2 anymore, but for now, this is a blocker for me (and I'd love if it could be fixed here instead).

**Comment by Lymphatus** [comment]
I made a few changes to the CMake configuration addressing this issue in the latest commits and tested on a stock Ubuntu 18.10. I might just test they work on Debian too (they should) and report back to you.

**Comment by nosilver4u** [comment]
I was using the latest commits for both libcaesium and caesiumclt and it didn't work for me on Debian 9, hope you can figure it out!

**Comment by Lymphatus** [comment]
Stock Debian uses another path for the standard libjpeg library, so was ok on my tests.
Indeed, if you have libjpeg on /usr/local/lib that has priority over mozjpeg. Moving the `link_directories(/usr/local/lib)` line solves the issue and seems to work well anyways.

I'm committing the change and close this issue.
Feel free to reopen it for any other problem.

**Comment by nosilver4u** [comment]
Yeah, I've compiled libjpeg from src via https://www.ijg.org/files/jpegsrc.v9c.tar.gz, which uses the /usr/local/lib location. Not sure where Debian puts it if you install from apt, but I suppose that would certainly make a difference. Thanks for looking into this, greatly appreciated!
