### ISSUE TITLE
Faild to run make command on Raspbian Buster

### ISSUE THREAD

**Issue by Kowa92** [Lymphatus/libcaesium#8]
Hello,

i'm trying to build _libcaesium_ for install _caesium-clt_ on RaspberryPi Buster.
But when i run main make of _libcaesium_, it stops with the following error:

`pi@raspberry:~/libcaesium/build $ make
Scanning dependencies of target caesium
[ 11%] Building C object caesium/CMakeFiles/caesium.dir/caesium.c.o
[ 22%] Building C object caesium/CMakeFiles/caesium.dir/error.c.o
[ 33%] Building C object caesium/CMakeFiles/caesium.dir/utils.c.o
[ 44%] Building C object caesium/CMakeFiles/caesium.dir/png.c.o
[ 55%] Building C object caesium/CMakeFiles/caesium.dir/vendor/lodepng.c.o
[ 66%] Building C object caesium/CMakeFiles/caesium.dir/jpeg.c.o
[ 77%] Linking C shared library libcaesium.so
/usr/bin/ld: cannot find -lturbojpeg
collect2: error: ld returned 1 exit status
make[2]: *** [caesium/CMakeFiles/caesium.dir/build.make:159: caesium/libcaesium.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: caesium/CMakeFiles/caesium.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

And i don't know how to solve it.. I didn't any package to fix it.

- Maybe can you help me to fix it?

PS I followed all the steps you wrote in the Readme file.

---------

PSS: Previously I solved another error, that is:

`pi@raspberry:~/libcaesium/build $ make
Scanning dependencies of target caesium
[ 11%] Building C object caesium/CMakeFiles/caesium.dir/caesium.c.o
[ 22%] Building C object caesium/CMakeFiles/caesium.dir/error.c.o
[ 33%] Building C object caesium/CMakeFiles/caesium.dir/utils.c.o
[ 44%] Building C object caesium/CMakeFiles/caesium.dir/png.c.o
[ 55%] Building C object caesium/CMakeFiles/caesium.dir/vendor/lodepng.c.o
[ 66%] Building C object caesium/CMakeFiles/caesium.dir/jpeg.c.o
[ 77%] Linking C shared library libcaesium.so
/usr/bin/ld: cannot find -ljpeg
`

I solved it by installing this package: 

`sudo apt-get install libjpeg62-turbo-dev`

Thank you.

**Comment by Lymphatus** [comment]
Hello,

Actually you need mozjpeg and not libjpeg-turbo. If you are on a Ubuntu machine (as it seems from the commands you provided), you can run the `./install.sh` command, which should install all the dependencies for you. You can find it in the root folder of the project.

Let me know if it works!

Cheers

**Comment by Kowa92** [comment]
I've just done these following steps:

_Get the code with `$ git clone https://github.com/Lymphatus/libcaesium.git`_

_If you don't have `mozjpeg` and `zopfli` you should run_

`
$ cd libcaesium
$ ./install.sh
`

_which will install the requirements._

But make command doesn't work.
It output the **first** and the **second** error together, that is those i mentioned above (`/usr/bin/ld: cannot find -ljpeg` and `/usr/bin/ld: cannot find -lturbojpeg`).

NB: I don't use Ubuntu but Raspbian Buster for RaspberryPi.

Thanks

**Comment by Lymphatus** [comment]
libcaesium tries to locate `-ljpeg` and `-lturbojpeg` at `/opt/mozjpeg`. Check if you have that folder with some *.so files in the `lib` folder. If not, probably the install command did not work as expected. Eventually, you can specify the mozjpeg folder by passing `-DMOZJPEG_PATH=/your/path`

**Comment by Kowa92** [comment]
> libcaesium tries to locate `-ljpeg` and `-lturbojpeg` at `/opt/mozjpeg`. Check if you have that folder with some *.so files in the `lib` folder. If not, probably the install command did not work as expected. Eventually, you can specify the mozjpeg folder by passing `-DMOZJPEG_PATH=/your/path`

Yes, now it works. I fixed it by creating a symbolic link inside `/opt/mozjpeg` directory named `lib` that points to `lib32` (don't know why this catched this name), as follows:

![Cattura](https://user-images.githubusercontent.com/64701419/80920824-a27b5000-8d72-11ea-84e1-de039ad56700.PNG)

PS: I have another request but i put it inside the correct repo.

Thank you.
