### ISSUE TITLE
Feature Request: TIFF Support

### ISSUE THREAD

**Issue by Saijin-Naib** [Lymphatus/libcaesium#9]
I know TIFF is a massive can of worms, but perhaps it could be investigated in a limited scope initially.

Say, DEFLATE-compressed TIFFs.

libtiff (which now incorporates libdeflate) should be able to not only compress/decompress faster than prior, but also has optional Level 12 compression (increased from Level 9 of zlib), and should out-perform/compress zlib at each Level.

**Comment by Lymphatus** [comment]
With version 0.15.0 there's a initial support for TIFF even though it's a bit limited on which files it can handle. For now it's handling RGB(A) files and supports Lzw, Deflate (levels 3, 6, 9) and Packbits.
